.\" Manpage for opendlv-logic-cfsd18-sensation-attention
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-logic-cfsd18-sensation-attention 1 "06 November 2017" "0.0.2" "opendlv-logic-cfsd18-sensation-attention man page"

.SH NAME
opendlv-logic-cfsd18-sensation-attention \- This microservice is undocumented.



.SH SYNOPSIS
.B opendlv-logic-cfsd18-sensation-attention --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-logic-cfsd18-sensation-attention --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)
