.\" Manpage for opendlv-logic-cfsd18-perception-detectcone
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-sim-cfsd18-perception-detectcone 1 "07 February 2018" "0.0.3" "opendlv-sim-cfsd18-perception-detectcone man page"

.SH NAME
opendlv-sim-cfsd18-perception-detectcone \- This microservice is undocumented.



.SH SYNOPSIS
.B opendlv-sim-cfsd18-perception-detectcone --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-sim-cfsd18-perception-detectcone --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)
