.\" Manpage for opendlv-logic-cfsd18-sensation-geolocator
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-logic-cfsd18-sensation-geolocator 1 "07 February 2018" "0.0.3" "opendlv-logic-cfsd18-sensation-geolocator man page"

.SH NAME
opendlv-logic-cfsd18-sensation-geolocator \- This microservice returns the global position based on a global position estimate and internal movement data.



.SH SYNOPSIS
.B opendlv-logic-cfsd18-sensation-geolocator --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-logic-cfsd18-sensation-geolocator --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

