.\" Manpage for opendlv-logic-cfsd18-action-vehsim
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-logic-cfsd18-action-vehsim 1 "07 February 2018" "0.0.3" "opendlv-logic-cfsd18-action-vehsim man page"

.SH NAME
opendlv-logic-cfsd18-action-vehsim \- This microservice is undocumented.



.SH SYNOPSIS
.B opendlv-logic-cfsd18-action-vehsim --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-logic-cfsd18-action-vehsim --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)
