.\" Manpage for opendlv-logic-cfsd18-autobrake
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-logic-cfsd18-autobrake 1 "08 August 2017" "0.0.1" "opendlv-logic-cfsd18-autobrake man page"

.SH NAME
opendlv-logic-cfsd18-autobrake \- This microservice keeps track of the simulated world state, in particular the absolute position of simulated agents and other entities.



.SH SYNOPSIS
.B opendlv-logic-cfsd18-autobrake --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-logic-cfsd18-autobrake --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

