.\" Manpage for opendlv-logic-cfsd18-cognition-brake
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-logic-cfsd18-cognition-brake 1 "06 November 2017" "0.0.2" "opendlv-logic-cfsd18-cognition-brake man page"

.SH NAME
opendlv-logic-cfsd18-cognition-brake \- This microservice is undocumented.



.SH SYNOPSIS
.B opendlv-logic-cfsd18-cognition-brake --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-logic-cfsd18-cognition-brake --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)
