.\" Manpage for opendlv-logic-cfsd18-action-motion
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-logic-cfsd18-action-motion 1 "06 November 2017" "0.0.2" "opendlv-logic-cfsd18-action-motion man page"

.SH NAME
opendlv-logic-cfsd18-action-motion \- This microservice is undocumented.



.SH SYNOPSIS
.B opendlv-logic-cfsd18-action-motion --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-logic-cfsd18-action-motion --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)
